version: '3.4'

services:
  catalog.api:
    environment:
      - DatabaseSettings__ConnectionString=mongodb://catalog.db:27017

  basket.api:
    environment:
      - CacheSettings__ConnectionString=basket.cache:6379
  
  discount.api:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - DatabaseSettings__ConnectionString=Server=discount.db;Port=5432;Database=DiscountDb;User Id=admin;Password=admin1234
  
  discount.db:
    environment:
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=admin1234
      - POSTGRES_DB=DiscountDb
  
  pgadmin:
    environment:
      - PGADMIN_DEFAULT_EMAIL=admin@maycon.com
      - PGADMIN_DEFAULT_PASSWORD=admin1234