version: '3.4'

services:
  catalog.db: 
    image: mongo
    container_name: catalog.db
    restart: always
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db

  catalog.api:
    image: ${DOCKER_REGISTRY-}catalogapi
    container_name: catalog.api
    environment:
        - ASPNETCORE_ENVIRONMENT=Development
    depends_on:
        - catalog.db
    ports:
        - "8000:80"
    build:
        context: .
        dockerfile: Catalog.API/Dockerfile
    restart: always

  mongo-seed:
    container_name: mongoseed
    build:
        context: Catalog.API/docker/mongo-seed
        dockerfile: Dockerfile
        args:
            - DATABASE_URI=mongodb://catalog.db:27017
            #- USERNAME=$MONGO_INITDB_ROOT_USERNAME
            #- PASSWORD=$MONGO_INITDB_ROOT_PASSWORD
    depends_on:
        - catalog.db
   
  pgadmin:
    image: dpage/pgadmin4
    ports:
      - "5050:80"
    volumes:
      - pgadmin_data:/root/.pgadmin

  basket.cache: 
    image: redis
    container_name: basket.cache
    restart: always
    ports:
      - "6379:6379"
    volumes:
      - cache:/data

  basket.api:
    image: ${DOCKER_REGISTRY-}basketapi
    container_name: basket.api
    environment:
        - ASPNETCORE_ENVIRONMENT=Development
    depends_on:
        - basket.cache
    ports:
        - "8001:80"
    build:
        context: .
        dockerfile: Basket.API/Dockerfile
    restart: always

  discount.api:
    image: ${DOCKER_REGISTRY-}discountapi
    build:
      context: .
      dockerfile: Discount.API/Dockerfile
    restart: always
    depends_on:
        - discount.db
    ports:
        - "8002:80"
  
  discount.db:
     image: postgres
     ports:
      - "5432:5432"
     volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  mongo_data:
  postgres_data:
  pgadmin_data:
  cache:
